version: '2.16.0'

# networks:
#   sjs:
#     driver: bridge
#     # external: true

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: sjs
    volumes:
      - "./db:/var/lib/postgresql/data"
    # networks:
    #   - sjs
    
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # networks:
    #   - sjs

  php:
    restart: always
    container_name: php
    image: php:fpm
    build: ./php
    ports:
      - 9000:9000
    volumes:
      - "./WebApp:/var/www/html"
    # networks:
    #   - sjs

  web:
    restart: always
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./WebApp:/var/www/html"
    depends_on:
      - php
    # networks:
    #   - sjs

  python_app:
    container_name: python_app
    image: python-app:3.9
    restart: always
    build: ./python_app
    ports:
       - "5000:80"
    volumes:  
      - ./python_app:/python_app
    depends_on:
      - db
    # networks:
    #   - sjs
      

  python_api:
    container_name: python_api
    image: python-api:3.9
    restart: always
    build: ./python_api
    ports:
       - "5001:80"
    volumes:  
      - ./python_api:/python_api
    depends_on:
      - web
    # networks:
    #   - sjs